include $(TOPDIR)/rules.mk

LUCI_TITLE:=HotspotOS Theme
LUCI_DEPENDS:=+luci-base +hotspotos-base
LUCI_PKGARCH:=all

PKG_NAME:=luci-theme-hotspotos
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_MAINTAINER:=HotspotOS Team <dev@hotspotos.com>
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
