#!/bin/sh /etc/rc.common
# HotspotOS Internet Client Service

START=25
STOP=75

USE_PROCD=1

start_service() {
    local enabled
    config_load hotspot-client
    config_get_bool enabled main enabled 0

    [ "$enabled" -eq 0 ] && return 0

    procd_open_instance
    procd_set_param command /usr/lib/hotspotos/client-auto.sh
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    logger -t hotspot-client "HotspotOS Internet Client started"
}

stop_service() {
    logger -t hotspot-client "HotspotOS Internet Client stopped"
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "hotspot-client"
}
